
`include "uvm_pkg.sv"
import uvm_pkg::*;

`include "common.sv"
`include "asynch_fifo.v"
`include "fifo_intf.sv"
`include "fifo_tx.sv"
`include "rd_drv.sv"
`include "rd_srq.sv"
`include "wr_drv.sv"
`include "wr_sqr.sv"
`include "wr_agent.sv"
`include "rd_agent.sv"
`include "fifo_seq_lib.sv"
//`include "top_sqr.sv"
//`include "top_seq_lib.sv"
`include "fifo_mon.sv"
`include "fifo_cov.sv"
`include "fifo_sbd.sv"
`include "top_sqr.sv"
`include "top_seq_lib.sv"
`include "fifo_env.sv"
`include "test_lib.sv"
`include "top.sv"
//`include "fifo_env.sv"
//`include "test.lib.sv"
//`include "top.sv"
